name: Build
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout	
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
        with:
          submodules: recursive
      - name: Build
        run: |
          ./gradlew run
      - name: Set Node.js 18.x
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 18.x
      - name: Run yarn install
        uses: borales/actions-yarn@31e8b9ba96946b034c571eb19c7cba0d668dc97e # v4
        with:
         dir: 'website'
         cmd: install # will run `yarn install` command
      - name: Run yarn build
        uses: borales/actions-yarn@31e8b9ba96946b034c571eb19c7cba0d668dc97e # v4
        with:
          dir: 'website'
          cmd: run build # will run `yarn test` command     
      - name: Merge
        run: |
          cp -a output/. website/public/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92 # 4.1.4
        with:
          branch: gh-pages
          folder: website/public
