name: Check JSON Schema

on:
  push:
  pull_request:

jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
      name: Configure npm caching
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/validate_json.yml') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Run JSON Validation
      working-directory: ./tools
      run: |-
        npm install
        node schemaCheck.js